### ISSUE TITLE
nodejs not compatible with gcc7

### ISSUE THREAD

**Issue by pohly** [ostroproject/meta-iot-web#44]
OE-core master recently switched to gcc7. When using that, nodejs fails to build.

To reproduce in refkit, use https://github.com/intel/intel-iot-refkit/pull/184 and set GCCVERSION_df-refkit-config = "7.%" in local.conf. We are staying on gcc6.x by default because of this build failure.

**Comment by nagineni** [comment]
Reproducible. Looks like an upstream issue.

**Comment by nagineni** [comment]
Issue has been fixed already in upstream Node.js. I am hoping that there will be a new LTS 6.x release with the fix soon.

**Comment by nagineni** [comment]
If it is urgent, I can cherry-pick the patch and add to the recipe.

**Comment by pohly** [comment]
Is this the only thing that still breaks in refkit when using gcc7? I haven't checked. If it is, then it's probably worthwhile to backport the patch and then switch to gcc7 also in refkit.
